import type { RelationModel, SqlCanvasProject, TableModel } from '@/domain/schema'
import { getColumnSqlType } from '@/lib/sql/types'
import { qualifiedTableName, quoteIdentifier } from '@/lib/sql/identifiers'

function buildTableSql(table: TableModel): string {
  const columnLines = table.columns.map((column) => {
    const chunks = [`${quoteIdentifier(column.name)} ${getColumnSqlType(column)}`]

    if (!column.nullable) {
      chunks.push('NOT NULL')
    }

    if (column.defaultValue.trim()) {
      chunks.push(`DEFAULT ${column.defaultValue.trim()}`)
    }

    if (column.isUnique && !column.isPrimary) {
      chunks.push('UNIQUE')
    }

    return `  ${chunks.join(' ')}`
  })

  const primaryColumns = table.columns.filter((column) => column.isPrimary)
  if (primaryColumns.length > 1) {
    const primaryKeys = primaryColumns.map((column) => quoteIdentifier(column.name)).join(', ')
    columnLines.push(`  PRIMARY KEY (${primaryKeys})`)
  } else if (primaryColumns.length === 1) {
    const primaryIndex = table.columns.findIndex((column) => column.id === primaryColumns[0].id)
    if (primaryIndex >= 0) {
      columnLines[primaryIndex] = `${columnLines[primaryIndex]} PRIMARY KEY`
    }
  }

  return [`CREATE TABLE ${qualifiedTableName(table.schema, table.name)} (`, columnLines.join(',\n'), ');'].join('\n')
}

function buildRelationSql(relations: RelationModel[], tableMap: Map<string, TableModel>): string[] {
  return relations
    .map((relation) => {
      const sourceTable = tableMap.get(relation.sourceTableId)
      const targetTable = tableMap.get(relation.targetTableId)

      if (!sourceTable || !targetTable) {
        return ''
      }

      const sourceColumn = sourceTable.columns.find((column) => column.id === relation.sourceColumnId)
      const targetColumn = targetTable.columns.find((column) => column.id === relation.targetColumnId)

      if (!sourceColumn || !targetColumn) {
        return ''
      }

      return [
        `ALTER TABLE ${qualifiedTableName(sourceTable.schema, sourceTable.name)}`,
        `  ADD CONSTRAINT ${quoteIdentifier(relation.constraintName)}`,
        `  FOREIGN KEY (${quoteIdentifier(sourceColumn.name)})`,
        `  REFERENCES ${qualifiedTableName(targetTable.schema, targetTable.name)} (${quoteIdentifier(targetColumn.name)})`,
        `  ON UPDATE ${relation.onUpdate}`,
        `  ON DELETE ${relation.onDelete};`,
      ].join('\n')
    })
    .filter(Boolean)
}

export function generateProjectSql(project: Pick<SqlCanvasProject, 'tables' | 'relations'>): string {
  const tableMap = new Map(project.tables.map((table) => [table.id, table]))
  const tableStatements = project.tables.map((table) => buildTableSql(table))
  const relationStatements = buildRelationSql(project.relations, tableMap)

  return [
    '-- Generated by SQL Canvas Modeler',
    'BEGIN;',
    ...tableStatements,
    ...relationStatements,
    'COMMIT;',
  ]
    .filter((line) => line.trim().length > 0)
    .join('\n\n')
}
